# Generated by Django 5.2.16 on 2026-08-24 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="classteacher",
            name="academic_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_teachers",
                to="school.academicclass",
            ),
        ),
        migrations.AddConstraint(
            model_name="classteacher",
            constraint=models.UniqueConstraint(
                fields=("academic_class", "teacher"),
                name="unique_class_teacher_assignment",
            ),
        ),
    ]
