# Generated by Django 5.2.16 on 2026-08-26 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0002_alter_classteacher_academic_class_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studymaterial",
            name="academic_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="materials",
                to="school.academicclass",
            ),
        ),
    ]
