# Generated by Django 5.2.16 on 2026-08-28 12:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0003_studymaterial_academic_class"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="classteacher",
            name="unique_class_teacher_assignment",
        ),
        migrations.AddConstraint(
            model_name="classteacher",
            constraint=models.UniqueConstraint(
                fields=("academic_class",), name="unique_class_teacher"
            ),
        ),
    ]
