# Generated by Django 5.2.16 on 2026-09-09 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0005_gradeboundary_schoolevent_auditlog_fee_payment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fee",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated if left blank",
                max_length=200,
                null=True,
            ),
        ),
    ]
