# Generated by Django 5.2.16 on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0006_alter_fee_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parentprofile",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name="parent_profiles",
                to="auth.user",
            ),
        ),
    ]
