# Generated by Django 5.2 on 2026-09-13 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0009_add_question_option_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicclass",
            name="next_class",
            field=models.ForeignKey(
                blank=True,
                help_text="The class students are promoted to after this class. Leave blank for final class (SS3).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_class",
                to="school.academicclass",
            ),
        ),
    ]
