# Generated by Django 5.2.16 on 2026-08-23 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="academic_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="school.academicclass",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="unique_id",
            field=models.CharField(
                blank=True,
                help_text="Admin-given ID for staff",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
    ]
