# Generated by Django 5.2.16 on 2026-08-23 10:47

from django.db import migrations


def create_missing_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('accounts', 'Profile')
    for user in User.objects.all():
        Profile.objects.get_or_create(user=user)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_profile_academic_class_profile_unique_id"),
    ]

    operations = [
        migrations.RunPython(create_missing_profiles),
    ]
