# Generated by Django 5.2.16 on 2026-08-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_profile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="activation_token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_activated",
            field=models.BooleanField(default=False),
        ),
    ]
