# Generated by Django 5.2.16 on 2026-08-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_profile_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("staff", "Staff"),
                    ("admin", "Admin"),
                    ("parent", "Parent"),
                ],
                default="student",
                max_length=10,
            ),
        ),
    ]
