# Generated by Django 5.2.16 on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_profile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("graduated", "Graduated"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
