# Generated by Django 5.2 on 2026-09-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_profile_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="matric_number",
        ),
        migrations.AddField(
            model_name="profile",
            name="admission_number",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated for students",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="unique_id",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated for staff (STF/XXX/YYYY)",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
    ]
