# Generated by Django 5.2 on 2026-09-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_remove_profile_matric_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="otp_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="otp_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="password_reset_token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
