# Generated by Django 5.2 on 2026-09-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_profile_otp_code_profile_otp_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="password_reset_token_created_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when reset token was generated",
                null=True,
            ),
        ),
    ]
